### ISSUE TITLE
Golden Mage Hand crashes the game when trying to plant a crop in low light level

### ISSUE THREAD

**Issue by NotSoSorry** [skylorbeck/MageHand#7]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/5/22, 8:45 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5998(net.minecraft.class_1268)" because "$$1" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.item.Item.use(Item:204)
	at net.minecraft.item.BlockItem.useOnBlock(BlockItem:54)
	at net.minecraft.item.ItemStack.useOnBlock(ItemStack:250)
	at website.skylorbeck.magehand.entity.goals.MageHandPlantSeedGoal.lambda$tick$0(MageHandPlantSeedGoal.java:60)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at website.skylorbeck.magehand.entity.goals.MageHandPlantSeedGoal.tick(MageHandPlantSeedGoal.java:57)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.tick(PrioritizedGoal:65)
	at net.minecraft.entity.ai.goal.GoalSelector.tickGoals(GoalSelector:119)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector:110)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:742)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2609)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:546)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2354)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:346)
	at website.skylorbeck.magehand.entity.MageHandAbstractEntity.tick(MageHandAbstractEntity.java:123)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:702)
	at net.minecraft.world.World.tickEntity(World:485)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:363)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:331)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1792.method_7836(class_1792.java:204)
	at net.minecraft.class_1747.method_7884(class_1747.java:54)
	at net.minecraft.class_1799.method_7981(class_1799.java:250)
	at website.skylorbeck.magehand.entity.goals.MageHandPlantSeedGoal.lambda$tick$0(MageHandPlantSeedGoal.java:60)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at website.skylorbeck.magehand.entity.goals.MageHandPlantSeedGoal.method_6268(MageHandPlantSeedGoal.java:57)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:742)
	at net.minecraft.class_1309.method_6007(class_1309.java:2609)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at website.skylorbeck.magehand.entity.MageHandAbstractEntity.method_5773(MageHandAbstractEntity.java:123)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: magehand:gold (website.skylorbeck.magehand.entity.MageHandGoldEntity)
	Entity ID: 1230
	Entity Name: Gold Mage Hand
	Entity's Exact location: 332.46, 97.74, 397.66
	Entity's Block location: World: (332,97,397), Section: (at 12,1,13 in 20,6,24; chunk contains blocks 320,-64,384 to 335,319,399), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.04, -0.04, 0.06
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.0d,Name:"stepheightentityattribute:stepheight"},{Base:16.0d,Modifiers:[{Amount:0.008949452125131537d,Name:"Random spawn bonus",Operation:1,UUID:[I;1424817691,1548767078,-2099585350,-715900801]}],Name:"minecraft:generic.follow_range"},{Base:0.25d,Name:"minecraft:generic.movement_speed"},{Base:5.0d,Name:"minecraft:generic.attack_damage"}],Brain:{memories:{}},CanPickUpLoot:0b,DeathTime:0s,FallDistance:0.0f,FallFlying:0b,Fire:0s,HandDropChances:[100.0f,0.085f],HandItems:[{Count:59b,id:"minecraft:potato"},{}],Health:10.0f,HurtByTimestamp:0,HurtTime:0s,Invulnerable:0b,LeftHanded:0b,Motion:[0.037445825787426244d,-0.03570900666477517d,0.06156617924746795d],NoGravity:1b,OnGround:0b,PersistenceRequired:0b,PortalCooldown:0,Pos:[332.4575196236431d,97.74403140764213d,397.6557106413921d],Rotation:[354.76035f,-1.7327496f],UUID:[I;1494144176,-49526095,-1433624958,-461563652],cardinal_components:{"requiem:ai_toggle":{inhibitors:[]},"requiem:entity_clerk":{refs:[]},"requiem:possessed_data":{selected_slot:0},"requiem:soul_holder":{removed_soul:0b}},startX:333.0d,startY:97.0d,startZ:400.0d}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['__Sorry'/1215, l='ServerWorld minecraft:overworld Conquest of the World', x=333.09, y=96.94, z=393.23]]
	Chunk stats: 4238
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 949987 game time, 1198126 day time
	Level name: Conquest of the World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 2904 (now: false), thunder time: 5067 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 12.4
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1982725056 bytes (1890 MiB) / 4261412864 bytes (4064 MiB) up to 4261412864 bytes (4064 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Plus Graphics
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x8a53
	Graphics card #0 versionInfo: Revision ID: 0x0007
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.73
	Memory slot #0 type: LPDDR4X
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.73
	Memory slot #1 type: LPDDR4X
	Virtual memory max (MB): 23552.00
	Virtual memory used (MB): 17821.52
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 6468.75
	JVM Flags: 3 total; -Xss1M -Xmx4064m -Xms256m
	Fabric Mods: 
		architectury: Architectury 4.4.68
		artifacts: Artifacts 7.0.3+fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.0.7
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 1.4.7
		betterend: Better End 1.1.1
		betternether: Better Nether 6.1.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		bookshelf: Bookshelf 13.0.13
		carrier: Carrier 1.10.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+8
		comforts: Comforts 1.1.2-1.18.2
		continuity: Continuity 1.1.0+1.18.2
		controlling: Controlling For Fabric 9.0+19
		copperarmorandtools: Copper Armor & Tools 1.9.2
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		dark-loading-screen: Dark Loading Screen 1.6.11
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easymagic: Easy Magic 3.3.0
		eatinganimationid: Eating Animation 1.8
		fabric: Fabric API 0.55.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.6+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.17+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.13+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.4+d8d7804a60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.2+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.2+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.1+e747827960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.6
		fallingtree: FallingTree 3.5.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		forgeconfigapiport: Forge Config API Port 3.2.0
		geckolib3: Geckolib 3.0.43
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		horseinfo: Horse Info 0.4.1-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		iconicwands: Iconic Wands 1.0.4
		immersive_portals: Immersive Portals 1.4.0
			imm_ptl_core: Immersive Portals Core 1.4.0
			q_misc_util: QMiscUtil 1.4.0
		indium: Indium 1.0.3+mc1.18.2
		inventorysorter: Inventory Sorter 1.8.7-1.18
			kyrptconfig: Kyrpt Config 1.4.5-1.18
				blue_endless_jankson: jankson 1.2.1
		ironchests: Iron Chests 1.6.1
			libgui: LibGui 5.4.1+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		journeymap-fabric: Journeymap 5.8.4
			journeymap-api-fabric: JourneyMap API 1.18.2-1.8-fabric-SNAPSHOT
		lootgoblins: Lootgoblins 1.0.8
		magehand: Magehand 1.1.2
		mavm: More Axolotl Variants Mod 1.0.7a
		megaparrot: Megaparrot 1.0.5
		minecraft: Minecraft 1.18.2
		miniminer: Miniminer 1.0.1
		modmenu: Mod Menu 3.2.2
		mousetweaks: Mouse Tweaks 2.22
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		oxidized: Oxidized 1.6.4
		pickupnotifier: Pick Up Notifier 3.2.0
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		puzzleslib: Puzzles Lib 3.3.5
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		repurposed_structures: Repurposed Structures 4.1.12+1.18.2
			omega-config: OmegaConfig 1.0.8
		requiem: Requiem 2.0.0-beta.8
			automatone: Automatone 0.7.0
			blabber: Blabber 0.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.3
			cardinal-components-world: Cardinal Components API (worlds) 4.1.3
			chime: Chime 1.2.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			fiber: fiber 0.23.0-2
			fiber2cloth: Fiber To Cloth 3.1.1
			impersonate: Impersonate 2.5.0
			locki: Locki 0.7.0
			playerabilitylib: Pal 1.5.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			requiem-core: Requiem-Core 2.0.0-beta.8
			requiemapi: Requiem-API 2.0.0-beta.8
			satin: Satin 1.7.2
		rightclickharvest: Right Click Harvest 2.0.7
		roughlyenoughitems: Roughly Enough Items 8.2.471
		rpg-hud: RPG-Hud 3.9.2
		sentimentality3: Sentimentality 3 1.5.0
		simple_veinminer: Cyan's Simple Veinminer 1.2.1
			completeconfig: CompleteConfig 1.3.3
		skinlayers: 3d Skin Layers 1.4.6-mc1.18.2
		skylorlib: SkyLib 1.3.35
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.4+mc1.18.2-build.39
			caffeineconfig: CaffeineConfig 1.1.0
		tokenablefurnaces: Tokenable Furnaces 1.1.6
		toms_storage: Tom's Simple Storage Mod 1.3.2
		toolstats: ToolStats 9.0.1
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.0
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.1.1
		trinkets: Trinkets 3.3.1
		visualworkbench: Visual Workbench 3.3.0
		waystones: Waystones 2.5.3
		wthit: wthit 4.10.3
		yigd: You're in Grave Danger 1.3.6
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['__Sorry'/1215, l='ServerWorld minecraft:overworld Conquest of the World', x=333.09, y=96.94, z=393.23]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 2
	Suspected Mods: Magehand (magehand)

**Comment by Sebas-Re** [comment]
I have a similar issue with gold hands, but the crash looks different
"Cannot invoke "net.minecraft.class_1657.method_31548()" because "player" is null"
https://pastebin.pl/view/d4bd99b5

**Comment by skylorbeck** [comment]
As with the original issue, that is caused by something changing how the on block use is handled. Someone did a restrictive assumption without checking their type

**Comment by skylorbeck** [comment]
And it wasn't me.
